import { Sidebar } from "@/app/components/Sidebar";
import "../../../globals.css";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import { NotificationContext } from "@/app/contexts/notification";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Brainz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <NotificationContext>
          <div className="relative">
            <div className="p-0 md:px-8 mx-auto flex">
              <Sidebar />
              <div className="w-full md:w-[calc(100%-243px)] md:pl-8 md:border-l-4 md:border-primary-350 ">
                <Header />
                <main>{children}</main>
              </div>
            </div>
          </div>
        </NotificationContext>
      </body>
    </html>
  );
}
