import { Sidebar } from "@/app/components/Sidebar";
import "../../../../globals.css";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import { SessionHeader } from "@/app/components/SessionHeader";
import { NotificationContext } from "@/app/contexts/notification";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Brainz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main>
          <NotificationContext>
            <div>
              {/* <SessionHeader /> */}
              {children}
            </div>
          </NotificationContext>
        </main>
      </body>
    </html>
  );
}
