import { SkeletonTheme } from "react-loading-skeleton";
import { NotificationContext } from "../contexts/notification";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Brainz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <NotificationContext>
          <SkeletonTheme baseColor="#5a646b" highlightColor="#858f96">
            {children}
          </SkeletonTheme>
        </NotificationContext>
      </body>
    </html>
  );
}
